### ISSUE TITLE
Scraping Decklist data

### ISSUE THREAD

**Issue by nrdietz** [4dcu-be/Machine-Learning-the-Gathering#1]
I found this reference as a way to capture deck lists from mtgtop8.com and I am looking to compare deck lists for the last ten years. 

From the documentation:

archetypes = {}
decks = {}

# First find all archetypes and the link to their details
for a in soup.find_all('a'):
    if "archetype" in a['href']:
        archetypes[a.string] = a['href']

pattern = re.compile("d=(\d+)")  # Regex to extract deck ID from url

# For each archetype get the deck IDs
for archetype, url in tqdm(archetypes.items()):
    current_url = base_url + url
    resp = requests.get(current_url)
    current_soup = BeautifulSoup(resp.text, 'html.parser')
    
    deck_urls = [a['href'] for a in current_soup.find_all('a') if 'event' in a['href'] and 'd=' in a['href']] 
    decks[archetype] =  [pattern.search(d).group(1) for d in deck_urls]

It looks like the website has updated since this was written and I don't have the most experience in web scraping (some with Reddit API). I am just looking for help to extract the list of decks as described [here](https://github.com/4dcu-be/Machine-Learning-the-Gathering/blob/master/MLtG.ipynb)

**Comment by sepro** [comment]
This was a relatively small issue, and has been fixed in the notebooks in the repository. Will update the code in the blog next time I work on it.

**Comment by sepro** [comment]
Do note that this works for decklists from the last 2 weeks and only those on the first page. It will need a fair bit of modification to pull in everything from the last decade.
